all:
  hosts:
    nfs01:
      ansible_host: 172.31.27.65
      ansible_user: ec2-user
    web02:
      ansible_host: 172.31.39.10
    web01:
      ansible_host: 172.31.34.99
    db01:
      ansible_host: 172.31.36.61 
      ansible_user: ec2-user
  
  children:
    webservers:
      hosts:
        web01:
        web02:
        
    dbservers:
      hosts:
        db01:
    storage:
      hosts:
        nfs01:

    vars:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: stockholm_key.pem

