---
- hosts: uat_webservers
- import_playbook: ../static-assignment/uat-webservers.yml

- name: Loadbalancers assignment
  hosts: lb
- import_playbook: ../static-assignment/loadbalancers.yml
  when: load_balancer_is_required 
